---
title: "Word Cloud Program on Shiny"
author: LearningSpoonsR
output: 
  flexdashboard::flex_dashboard:
  runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
source("../../LSR.R")
setLang("kr")
library(tm); library(SnowballC); library(KoNLP); library(pdftools); library(cld3)
library(ggplot2); library(dplyr); library(wordcloud2); library(RColorBrewer)
```

Inputs {.sidebar}
-------------------------------------

```{r}
selectInput(inputId = "theFile", label = "Choose a file",   
            choice = list.files("../script/"))  
```
 
Column {data-width=500}
-------------------------------------
    
### Barplot  
 
```{r}  
renderPlot({
  docs <- getDocs2(paste0("../script/", input$theFile))
  freqTable <- cleanDocsGenerateFreqTable(docs, attr(docs, "lang"))
  g <- ggplot(head(freqTable,20)) +
    geom_bar(aes(x = reorder(word, freq), y = freq), stat="identity") +
    theme(axis.text = element_text(size = 16)) +
    labs(x = "Word", y = "Frequency") + 
    coord_flip()
  print(g)
})  
```   
  
Column {data-width=500}  
-------------------------------------
  
### Word Cloud  

```{r, warning = FALSE, fig.width=18, fig.height=18}
renderWordcloud2({
  docs <- getDocs2(paste0("../script/", input$theFile))
  freqTable <- cleanDocsGenerateFreqTable(docs, attr(docs, "lang"))
  w <- wordcloud2(freqTable, color = "random-light", backgroundColor = "grey")
  print(w)
})
```

  
