---
title: "M47 - SNS marketing"
author: "learningSpoons"
date: "`r Sys.Date()`"
output: flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
knitr::opts_chunk$set(echo = TRUE)
```

Setup & Infile  
=====================================  
    
Column {data-width=500}
-------------------------------------
    
```{r, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(readxl)
library(stringr)
library(lubridate)
library(plotly)
dataset <- read.csv("dataset.csv", stringsAsFactors = FALSE)
str(dataset)
```

```{r}
unique(dataset$acct)
dataset$acct[dataset$acct %in% c("naver.con", "nvaer.com")] <- "naver.com"
dataset$acct[dataset$acct %in% c("hanmail.net", "hanmauk.net")] <- "daum.net"
dataset$date <- as.Date(dataset$date)
dataset$acct <- as.factor(dataset$acct)
```  

Column {data-width=500}
-------------------------------------
   
```{r}
dataset$fb     <- str_detect(dataset$path, "페이스북")
dataset$blog   <- str_detect(dataset$path, "블로그")
dataset$web    <- str_detect(dataset$path, "홈페이지")
dataset$jiin   <- str_detect(dataset$path, "지인")
dataset$search <- str_detect(dataset$path, "검색")
dataset$cafe   <- str_detect(dataset$path, "카페")
dataset$insta  <- str_detect(dataset$path, "인스타")
```

```{r}
# count by acct  
dataset %>%
  group_by(acct) %>%
  summarise(count = length(acct)) %>%
  arrange(desc(count))
# mutate acctType
dataset <- dataset %>%
  mutate(acctType = 
           ifelse(acct=="naver.com", "naver",
                  ifelse(acct=="gmail.com", "gmail",
                         ifelse(acct=="hanmail.net", "daum",
                                ifelse(acct=="daum.net", "daum", "other")))))
dataset$acctType <- as.factor(dataset$acctType)
dataset_acctType <- dataset %>%
  group_by(acctType) %>%
  summarise(
    fb = sum(fb), blog = sum(blog), web = sum(web), 
    jiin = sum(jiin), search = sum(search),
    cafe = sum(cafe), insta = sum(insta))
dataset_acctType <- dataset_acctType[1:4,]
```

Time Series by month      
=====================================  
    
Column {data-width=500}
-------------------------------------

```{r}
dataset_month <- dataset %>%
  group_by(Y = year(date), M = month(date)) %>%
  summarise(
    fb = sum(fb), blog = sum(blog), web = sum(web), 
    jiin = sum(jiin), search = sum(search),
    cafe = sum(cafe), insta = sum(insta)) %>%
  mutate(Date = as.Date(paste(Y, M, 1, sep = "-")))
```

```{r}
# multiple geom_line
fig1 <- ggplot(dataset_month, aes(x = Date)) + 
  geom_line(aes(y = fb, colour = "fb")) + 
  geom_line(aes(y = blog, colour = "blog")) + 
  geom_line(aes(y = web, colour = "web")) + 
  geom_line(aes(y = jiin, colour = "jiin")) + 
  geom_line(aes(y = cafe, colour = "cafe")) + 
  geom_line(aes(y = insta, colour = "insta")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  scale_x_date(breaks = dataset_month$Date) +
  labs(x = "Month", y = NULL)
```

Column {data-width=500}
-------------------------------------

```{r}
ggplotly(fig1)
```


Piechart - All time      
=====================================  

Column {data-width=500}
-------------------------------------

```{r}
# All Time
df <- data.frame(
  channel = colnames(dataset_month)[3:9],
  freq = colSums(dataset_month[, c(3:9)]),
  stringsAsFactors = FALSE)
# M91.page 39 - pie-chart
fig2 <- ggplot(df, aes(x = "", y = freq, fill = factor(channel))) +
  geom_bar(width = 1, stat = "identity") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust=0.5)) +
  labs(fill="channel", x=NULL, y=NULL) + 
  coord_polar(theta = "y", start=0)
```

Column {data-width=500}
-------------------------------------

```{r}
print(fig2)
```

Piechart - Facet by Month      
=====================================  

Column {data-width=500}
-------------------------------------

```{r}
# facet by month
# googled "r facet piechart"
# https://stackoverflow.com/questions/25372055/how-can-i-use-facet-wrap-using-pie-charts
library(reshape2) 
dataset_month_long <- 
  data.frame(Date = dataset_month$Date, dataset_month[,3:9]) %>% 
  melt(id = "Date") # Change it to "long" type - not tidy!
fig4 <- 
  ggplot(dataset_month_long,
         aes(x = 1, y = value, fill = variable)) + 
  geom_bar(stat = "identity", 
           color = "black",
           position = position_fill()) +
  coord_polar(theta = "y") + 
  theme(axis.ticks = element_blank(),
        axis.text.x = element_text(colour='black'),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.title = element_text(hjust=0.5)) + 
  scale_y_continuous(
    breaks = cumsum(dataset_month_long$value) - dataset_month_long$value/2,
    labels = dataset_month_long$variable) +
  facet_wrap( ~ Date)
```

Column {data-width=500}
-------------------------------------

```{r}
print(fig4)
```



Piechart - Facet by Month      
=====================================  

Column {data-width=500}
-------------------------------------

```{r}
dataset_acctType_proportion <-
  data.frame(
    acctType = dataset_acctType$acctType,
    round(dataset_acctType[,2:8]/rowSums(dataset_acctType[,2:8]), 2),
    subtotal = rowSums(dataset_acctType[,2:8])) 
dataset_acctType_proportion <- dataset_acctType_proportion %>% arrange(desc(subtotal))
dataset_acctType_proportion
table(dataset$acct)
```

```{r}
dataset_acctType_long <- 
  data.frame(acctType = dataset_acctType$acctType, dataset_acctType[,2:8]) %>% 
  melt(id = "acctType") # Change it to "long" type - not tidy!
fig5 <- 
  ggplot(dataset_acctType_long,
         aes(x = 1, y = value, fill = variable)) + 
  geom_bar(stat = "identity", 
           color = "black",
           position = position_fill()) +
  coord_polar(theta = "y") + 
  theme(axis.ticks = element_blank(),
        axis.text.x = element_text(colour='black'),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.title = element_text(hjust=0.5)) + 
  scale_y_continuous(
    breaks = cumsum(dataset_acctType_long$value) - dataset_acctType_long$value/2,
    labels = dataset_acctType_long$variable) +
  facet_wrap( ~ acctType)
```

Column {data-width=500}
-------------------------------------

```{r}
print(fig5)
```
