---
title: "M32 Practice"  
output: flexdashboard::flex_dashboard
---

Page 1 {data-orientation=rows}
=====================================     
   
Row {data-height=500}
-------------------------------------

### Scatter plot 

```{r}
library(ggplot2)
library(plotly)
a1 <- ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(aes(color = class))
a2 <- a1 + geom_smooth()
ggplotly(a2)
```

Row {data-height=500}
-------------------------------------
   
### Table  

```{r}
library(dplyr)
library(kableExtra)
b <- mpg %>%
  group_by(class) %>%
  summarise(hwy = round(mean(hwy), 1),
            cty = round(mean(cty), 1)) %>%
  arrange(desc(hwy)) %>% t()
kable(b) %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)
```   

Ref: <https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html>    

### Box plot  

```{r}  
c <- ggplot(mpg) + geom_boxplot(aes(x = class, y = hwy, fill = class)) + coord_flip()
ggplotly(c)
```

Page 2     
=====================================  

```{r}
a3 <- a1 + facet_wrap(~ class)
ggplotly(a3)
```