---
title: "Rich Country = Live Longer??"  
runtime: shiny   
output:  
  flexdashboard::flex_dashboard:  
    source: embed    
---


```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
```

```{r, echo=FALSE}
lifeCountry <- read.csv("data/lifeCountry.csv", 
                        stringsAsFactors = FALSE)[,-1]
```

Selections {.sidebar}
===============================
  
--------------------------------------    

```{r}
checkboxGroupInput("OECDness", "OECD", c("OECD","non-OECD"), selected = "OECD")
checkboxGroupInput("Continents", "Continents", 
                   unique(lifeCountry$Continent), selected = unique(lifeCountry$Continent))
sliderInput("gdpRange", "Range of Country GDP (USD)",
            min = 0, max = 100000, value = c(10000, 100000))
```

--------------------------------------    

```{r}
checkboxInput("doBubble", "Point proportional to population", value=FALSE)
checkboxInput("doLogX", "Set X-axis into log scale", value=FALSE)
checkboxInput("doSmooth", "Add trend line", value=FALSE)
checkboxInput("doShape", "Varying shape", value=FALSE) 
```
  
Final Project: `ggplot`+`API`+`rmarkdown`+`shiny`+`flexdashboard`  
===================================== 

```{r}
renderPlot({
  if (length(input$OECDness)==0) {
    print("SELECT OECD and/or non-OECD countries")
  } else if (length(input$OECDness)==2) {
    # do nothing
  } else if (input$OECDness=="OECD") {
    lifeCountry <- subset(lifeCountry, !is.na(OECD_GDP))
  } else {
    lifeCountry <- subset(lifeCountry, is.na(OECD_GDP))
  }
  lifeCountry <- subset(lifeCountry, 
                        Continent %in% input$Continents)
  lifeCountry <- subset(lifeCountry, 
                        (GDP_per_Capita >= input$gdpRange[1]) | (GDP_per_Capita <= input$gdpRange[2]))
  myGgplot <- ggplot(lifeCountry, 
                     aes(x=GDP_per_Capita, y=Life.Expectancy, color=Continent)) +
    geom_text(aes(label=Country), size=4, vjust=1.5) +
    geom_point() +
    xlab("GDP per Capita in 2017 (in US Dollars)") +
    ylab("Life Expectancy at Birth in 2016") + 
    ggtitle("2D space cannot limit our imagination!")
  if (input$doBubble) { myGgplot <- myGgplot + geom_point(aes(size=Population)) }
  if (input$doLogX)   { myGgplot <- myGgplot + scale_x_log10() + xlab("GDP per Capita (log-scale)")}
  if (input$doSmooth) { myGgplot <- myGgplot + geom_smooth(method='lm', se=TRUE, size=1) } 
  if (input$doShape)  { myGgplot <- myGgplot + geom_point(aes(shape=Continent))}
  myGgplot
})
```

