---
title: "Glossary "
author: "LearningSpoonsR"
date: "`r Sys.Date()`"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    source: embed
---

```{r setup, include=FALSE}
# https://acemk.shinyapps.io/M94-glossary/
library(flexdashboard)
library(readxl)
library(dplyr)
Sys.setenv(LANG = "kr")
Sys.setlocale("LC_ALL", "Korean")
options(stringsAsFactors = FALSE)
xlsxPath      <- "data/glossary.xlsx"
dataSource    <- xlsxPath %>% read_excel(sheet = "dataSource", col_names = F)
preProcessing <- xlsxPath %>% read_excel(sheet = "preProcessing", col_names = F)
```
  
Cheatsheet for Project Design     
===================================== 

Column 1 {data-width=100}
------------------------------------
### I. 데이터 소스  

```{r}
radioButtons("dataSource", 
             label = "데이터는 어디에 있습니까? ",
             choices = c("Local File", "Package", "API", "Scraping", "Multiple"),
             selected = "Local File")
```

    
```{r}
renderText({
  c(length(input$dataSource), input$dataSource)
})
```

Column 2 {data-width=100}
------------------------------------
### II. 전처리  

```{r}
"Hello"
```

tidy
select
filter
missing values
timeseries

Column 3 {data-width=100}
------------------------------------
### III. 분 석 

```{r}
"Hello"
```

집계  
table  
ggplot  
 - scatter  
 - boxplot   
 - barplot    
wordcloud
번역
dygraph  

Column 4 {data-width=100}
------------------------------------
### IV. 결과물 생성  

```{r}
"Hello"
```

html  
docx  
pdf  
dashboard  

beamer  
ioslide/slidy  

shiny  

Column 5 {data-width=100}
------------------------------------
### V. 공 유  

slideshare.net  
email  
slack   
github.io  
shinyapps.io  

Column 6 {data-width=100}
------------------------------------
### VI. Replay  

함수
process 화  


Module Glossary      
===================================== 

### Module Glossary

```{r}
"Hello"
```

Package Glossary     
===================================== 

### Package Glossary    

```{r}
"Hello"
```

Trouble Shooting       
===================================== 

```{r}
"Hello"
```


